import path from "path";

import { defineConfig } from "vitest/config";

/** Pliki graniczne (Prisma, API, orchestracja) — testowane integracyjnie / E2E, nie w progach unit. */
const COVERAGE_EXCLUDE = [
  "src/lib/**/*.d.ts",
  "src/lib/auth.ts",
  "src/lib/auth.config.ts",
  "src/lib/seed-default-categories.ts",
  "src/lib/ai/complete.ts",
  "src/lib/ai/config.ts",
  "src/lib/ai/generate-insights.ts",
  "src/lib/ai/load-insight-transactions.ts",
  "src/lib/ai/build-insight-payload.ts",
  "src/lib/ai/save-ai-insight.ts",
  "src/lib/ai/load-ai-insight-history.ts",
  "src/lib/ai/resolve-workspace-ai.ts",
  "src/lib/ai/run-generate-insight.ts",
  "src/lib/ai/build-discretionary-insight-payload.ts",
  "src/lib/ai/generate-discretionary-insight.ts",
  "src/lib/ai/run-generate-discretionary-insight.ts",
  "src/lib/ai/save-discretionary-ai-insight.ts",
  "src/lib/ai/load-discretionary-ai-insight.ts",
  "src/lib/ai/parse-discretionary-insight-params.ts",
  "src/lib/ai/discretionary-insight-types.ts",
  "src/lib/ai/prompts/discretionary-insight.ts",
  "src/lib/ai/describe-ai-categorization.ts",
  "src/lib/ai/run-categorization.ts",
  "src/lib/ai/ai-target-transactions.ts",
  "src/lib/ai/status.ts",
  "src/lib/ai/apply-assignments.ts",
  "src/lib/analytics/load-dashboard.ts",
  "src/lib/analytics/fetch-dashboard-opportunities.ts",
  "src/lib/research/run-opportunity-research.ts",
  "src/lib/research/search-tavily.ts",
  "src/lib/research/config.ts",
  "src/lib/research/count-daily-research.ts",
  "src/lib/research/map-research-view.ts",
  "src/lib/research/opportunity-research-props.ts",
  "src/lib/optimization/map-opportunity-cards.ts",
  "src/lib/optimization/load-optimization-data.ts",
  "src/lib/optimization/load-budget-spent.ts",
  "src/lib/optimization/upsert-opportunities.ts",
  "src/lib/optimization/opportunity-upsert-data.ts",
  "src/lib/optimization/run-detection.ts",
  "src/lib/transactions/load-workspace-transfer-pairs.ts",
  "src/lib/transactions/build-transaction-table-rows.ts",
  "src/lib/transactions/find-similar-transaction-ids.ts",
  "src/lib/transactions/bulk-category-client.ts",
  "src/lib/transactions/bulk-category-targets.ts",
  "src/lib/transactions/execute-bulk-category-update.ts",
  "src/lib/transactions/load-transactions-page.ts",
  "src/lib/transactions/fetch-transactions-page-bundle.ts",
  "src/lib/transactions/transaction-list-extra-where.ts",
  "src/lib/transactions/validate-bulk-update.ts",
  "src/lib/transactions/has-bulk-selection.ts",
  "src/lib/transactions/upsert-counterparty-rule.ts",
  "src/lib/analytics/load-dashboard-metrics.ts",
  "src/lib/analytics/load-dashboard-page.ts",
  "src/lib/analytics/load-dashboard-extras.ts",
  "src/lib/analytics/dashboard-types.ts",
  "src/lib/analytics/dashboard-extras.ts",
  "src/lib/analytics/dashboard-params.ts",
  "src/lib/categories/category-transaction-counts.ts",
  "src/lib/categories/ensure-transfer-category.ts",
  "src/lib/privacy/privacy-amounts-storage.ts",
  "src/lib/mbank/sync-categories.ts",
  "src/lib/ai/run-mbank-verify-batch.ts",
  "src/lib/ai/prompts/mbank-verify.ts",
  "src/lib/review/load-review-queue.ts",
  "src/lib/review/map-review-items.ts",
  "src/lib/review/persist-review-decision.ts",
  "src/lib/review/resolve-review-category.ts",
  "src/lib/review/build-review-queue-where.ts",
  "src/lib/review/review-bulk-actions.ts",
  "src/lib/import/load-import-freshness.ts",
  "src/lib/discretionary/load-discretionary-page.ts",
  "src/lib/discretionary/load-opcjonalne-page.ts",
  "src/lib/discretionary/assemble-discretionary-page.ts",
  "src/lib/discretionary/fetch-discretionary-data.ts",
  "src/lib/discretionary/build-discretionary-page-result.ts",
  "src/lib/discretionary/map-discretionary-periods.ts",
  "src/lib/discretionary/aggregate-discretionary-merchants.ts",
  "src/lib/discretionary/map-transaction-for-discretionary.ts",
  "src/lib/discretionary/discretionary-tx.ts",
  "src/lib/discretionary/expense-coverage-percent.ts",
  "src/lib/discretionary/types.ts",
  "src/lib/discretionary/fetch-discretionary-data.ts",
  "src/lib/discretionary/load-discretionary-page.ts",
  "src/lib/discretionary/load-opcjonalne-page.ts",
  "src/lib/discretionary/assemble-discretionary-page.ts",
  "src/lib/discretionary/build-discretionary-page-result.ts",
  "src/lib/discretionary/map-discretionary-periods.ts",
  "src/lib/discretionary/map-transaction-for-discretionary.ts",
  "src/lib/import/load-import-freshness.ts",
  "src/lib/review/review-bulk-actions.ts",
  "src/lib/recurring/**/*.ts",
];

export default defineConfig({
  test: {
    environment: "node",
    include: ["tests/**/*.test.ts"],
    coverage: {
      provider: "v8",
      reporter: ["text", "html", "lcov"],
      include: ["src/lib/**/*.ts"],
      exclude: COVERAGE_EXCLUDE,
      thresholds: {
        lines: 80,
        branches: 75,
        functions: 80,
        statements: 80,
      },
    },
  },
  resolve: {
    alias: { "@": path.resolve(__dirname, "./src") },
  },
});
